title: OpenWrt devices
baseurl: "/openwrt-devices" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

current_release: 18.06.2


# Build settings
markdown: kramdown
#theme: jekyll-theme-cayman

header_pages:
   - devices.md

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
